travis:
  secure:
    BINSTAR_TOKEN: Vw88+43lDhesVz3BUDc8KdoIuYopFmW6HIRWmyceAfhbrEHMQBo100saWyD23AcXfvJztWNC4ssPycCoEeMtUKJiroNbcpTlnXzUlknHLC83RiuxvGzcfaf/y15dN+DqC4WnYmIrFwU4pg/MVMMPp5DnPOslb4wCfxbzTTppgRfEe8OUAqBRuehOIuRoRI618HPGlaVNPR9qFNBEwhWg8eGRDYEd3FCUcZrcIV8BamVAg0vMKGTllv0UlN1SgbApY8axBrbvdhNSmZr8UQEHL/hFm7GAxQGiF8IOZN4k97x3bv2PabS9uQHGup8gHDsH1GaS9iWibXaKC/xvUu+9kiuZUv2/x1U4fUmgw7mraU8UsfrUdE1Saw+GnfNWFpRDFZYZz4gSZ1yBBWDEBayAegzI4t7VZLdsfV2o+AmGsRhyGY/i4T90zKH23/QpvGdYHlZyxe84cItHdqBmdoDJ43mHxMdZkaaBLlWhcfafFxQLdYOU4psxgyZeZzH8aDb185yoHWfUoMqIY+Hn+gnxhvN4a/fZbcPpCZ2zN6RSQYV8B09oSHK63h++yiU1RnDXLJteMl/oZ8ArUP0cP+USi1wIzqCQWobckTCWSoZDDrfY59/V/C4IQUxdOBEHB4JpJHaykD+kTsYgKuQTTLjOVNSOjX68kTh2csPmVGpLd/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
