travis:
  secure:
    BINSTAR_TOKEN: KcbExqbCDRTCTJWkv2IXgIHwOnYwWqbBlFrWKSUeWWrkFuVnYJMqz5f0mZSxhxUOpQOJTRRR4Fte2pILQX/P2AQfaB6Cc750d8632dKSn1djsff3mTVHRINzQAHxdyYw3hh4PWysMx1L0y9eK8xSrJh5xLrzxufYz1sEfE2kEgKWlyUCCwjzCuk+GpfEla4pxnKcg0FgCFU8LDj64dr/i2gqXOQ/SBP6oygtDbt5md1vWPlMb/KzFR81RE7mVOKntGBJnD8XHdum7Fs0E0XR1HKVfjM1jK6n2+zJ2j4voEppxIbgOXoHVH1Z3dH5F/vzFb+bAUcEvvcktOxG9UeyEUCtUurLrvLbzxq1U6cJzivtRNAsZ8k3UWyhia1LeBS8vH7u7tSJRVkuX6KvR8JYCOfO+viI+betvEQHyeZ8rD6WzZchagCyZeLoAnrzeUHyOXWBhinpLzM5r7dkjAKOIrNVy3tstfXCyS108Cj43Ajis6MAexBQZApriWwAeNc3jFbyIHZafYTgqHp+RjwGpZfcuxq3dzDGokl3HoUyVzPyf2fAIItwUT4j+wlzki8P6PDB2g4hB4cZSuF6gPs3LhzJLlw8+K4bTjU67MyAJStWnaOObOHvAc6YouAm95M9nY9VTMDZXNkLJ2T8azW6Yk91+/pKEM+gMMo1hNyDHAA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
