travis:
  secure:
    BINSTAR_TOKEN: FucNLBX/vHcgZaQWESc0G0i4RpCRpV9By08zdfjKe7Yo//2wl+tP67B2RPbk2aT7XMnll5vssOFKI83IzxCYTuxR+co34blhTGFGqJLud85a5hgAP7bROA+PuevB6NMVgr0mAs9IYmBcfC+eFYjIGGHtGtjiPR4Z4+HxXj38JJYz5zC1PtdCaUNr+3x1IRvdqIzXgeQtNU9CejNn2Rw2OnXIPH30CWjhSzLEez543RWeE/LjDH1zEj1ZpfxlAuwhFvDbQrSxBp932krzVhOE1kNruKrlDgHOkuAPXHbdKMx/dKgbWQs0mq0j5ymsDdq46OtdOUJTbpiDsUMOBq6IlG6Ftsfa1I3gAuI2RLQzlWtzqH0wCYculzCrsPVdqqaOCOLze7drAEIPsJSoVD2G2NqQKZ8Qs/BCY4OdgoF/Gq70PzCfMrAzbGaVvzDslinMCEDQI+aJq+ebKSHbCIo58hE3sBWEbaAQH9pvSJHHCoBQ91buO4b7iH0FBlIfkIuERZI2PK7OHd3zTZgCwksahbCrCiwnlZs5GubBfd2sr/xMfabEnqJ1jQ6fe6CRsHSggjiGOP6+3bePWkKtoDaGn4fmWDHoZpgfzVhpPNPnnGQNl/YCt/wSMa5TDo8MeUg/vAv+wXxbXaX3VG4qapAmRpCP+Kf3lbMHqJx13vF+5rk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
